---
- hosts: ndfc_servers
  gather_facts: false
  tasks:
    - name: Get all fabrics
      cisco.dcnm.dcnm_rest:
        method: GET
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics"
      register: result
    - debug:
        var: result