- name: Update qos5mbit custom field on GigabitEthernet3
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    netbox_url: "http://ciscolive-netbox.berlab.de"
    api_token: "{{ lookup('env', 'api_token') }}"
  tasks:
    - name: Update interface custom field qos5mbit to true
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ api_token }}"
        data:
          device: "{{ device_name }}"
          name: "{{ interface_name }}"
          custom_fields:
            qos5mbit: true
        state: present

    - name: Show update result
      debug:
        msg: "Interface {{ interface_name }} on device {{ device_name }} updated with qos5mbit=true"
